### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by Matt-Lepley** [hungryangie/fhone#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by hungryangie** [comment]
I've added the tags, so exciting to see it responsive!

**Comment by Matt-Lepley** [comment]
Awesome job! 

You can close this issue now that it has been fixed!
